language: csharp
sudo: false
env:
  - MONO_THREADS_PER_CPU=2000 DNX_TRACE=1
os:
  - linux
  - osx
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - libunwind8
script:
  - ./build.sh --quiet verify